apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-plus-ingress
  namespace: nginx-plus-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-plus-ingress
  template:
    metadata:
      labels:
        app: nginx-plus-ingress
     annotations:
       prometheus.io/scrape: "true"
       prometheus.io/port: "9113"
    spec:
      serviceAccountName: nginx-plus-ingress
      containers:
      - image: nginx-plus-ingress:{{VERSION}}
        imagePullPolicy: Always
        name: nginx-plus-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
       - name: prometheus
         containerPort: 9113
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 101 #nginx
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -alsologtostderr
          - -nginx-plus
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-plus-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret-plus
         #- -v=3 # Enables extensive logging. Useful for troubleshooting.
         - -report-ingress-status
         - -external-service=nginx-plus-ingress
         - -enable-leader-election
         - -enable-prometheus-metrics
         - -enable-custom-resources
         - -health-status
 